# Generated by Django 4.2.2 on 2024-06-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diario',
            name='title',
        ),
        migrations.AddField(
            model_name='diario',
            name='description',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='diario',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
